GOOGLE_OAUTH_CLIENT_ID = "cient-id"
GOOGLE_OAUTH_CLIENT_SECRET = "cient-secret"
GOOGLE_OAUTH_REDIRECT_URI = "redirect-uri"

[DATABASE]
HOST = "127.0.0.1"
PORT = "5432"
DB_NAME = "shirinibede"
USERNAME = "username"
PASSWORD = "password"
