openapi: 3.0.0
info:
  title: shirini-bede API
  version: 1.0.0
  description: API documentation for the shirini-bede application.
servers:
  - url: http://localhost:8080/api
paths:
  /health:
    get:
      summary: Health check
      tags:
        - Health
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /auth/google:
    post:
      summary: Login with Google OAuth
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_token:
                  type: string
                  description: Google ID token
              required:
                - id_token
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: Internal server error
  /teams:
    post:
      summary: Create a new team
      tags:
        - Team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Engineering Team"
              required:
                - name
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Team created
          content:
            application/json:
              schema:
                type: object
                properties:
                  join_url:
                    type: string
                    example: "/join/123e4567-e89b-12d3-a456-426614174000"
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      summary: List teams for the authenticated user
      tags:
        - Team
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamView'
        '500':
          description: Internal server error
  /join/{token}:
    post:
      summary: Join a team by token
      tags:
        - Team
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: Join token for the team
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Joined team successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Joined team successfully"
        '404':
          description: Team not found
        '500':
          description: Internal server error
  /claims:
    post:
      summary: Create a new achievement claim
      tags:
        - Claim
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                team_id:
                  type: string
                  format: uuid
                claimed_for:
                  type: string
                  format: uuid
                message:
                  type: string
                  example: "Completed major project"
              required:
                - team_id
                - claimed_for
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Claim created
          content:
            application/json:
              schema:
                type: object
                properties:
                  claim_id:
                    type: string
                    format: uuid
        '400':
          description: Bad request
        '500':
          description: Internal server error
    get:
      summary: List pending claims for the authenticated user
      tags:
        - Claim
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of pending claims
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClaimView'
        '500':
          description: Internal server error
  /votes:
    post:
      summary: Vote on a claim
      tags:
        - Vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                claim_id:
                  type: string
                  format: uuid
                vote:
                  type: boolean
                  description: true=upvote, false=downvote
              required:
                - claim_id
                - vote
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Vote recorded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Vote recorded"
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        avatar_url:
          type: string
          format: uri
        created_at:
          type: string
          format: date-time
    TeamView:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        join_token:
          type: string
        created_by:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
    ClaimView:
      type: object
      properties:
        id:
          type: string
          format: uuid
        team_id:
          type: string
          format: uuid
        claimed_by:
          type: string
          format: uuid
        claimed_by_name:
          type: string
        claimed_for:
          type: string
          format: uuid
        claimed_for_name:
          type: string
        message:
          type: string
